export { default as AboutBgImage } from './BgImage';
export { default as HeaderContent } from './HeaderContent';
export { default as GlanceDescription } from './GlanceDescription';
export { default as GlanceProfilePic } from './GlanceProfilePic';
export { default as GlanceImpression } from './GlanceImpression';
export { default as DetailsPrompt } from './DetailsPrompt';
export { default as DetailsInfo } from './DetailsInfo';
export { default as TotalReviews } from './TotalReviews';
export { default as Review } from './Review';
